import { Metadata } from "next";

export const metadata:Metadata = {
  title: {
    default: 'Next.js Series', //this will be used as the default title for all its children pages
    template: '%s | Next.js Series', // %s will be replaced with the titile of the children page and rest will be appended
    absolute: 'This is a absolute title'// use this in pages where we want to break free from the template set by the outer pages/layout
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
